Spring Object
The-Newcastle-Gang/SpeedFun pull request #47
Opened 2024-02-23 16:25 UTC by JunkyX1122

Spring thing.
- Vector3 bounceForce                                                     : initial bounce impulse force.
- float springActiveTime;                                                  : spring cooldown / how long force is applied to player.
- std::map<const GameObject*, float> pushableObject; : handles cooldown and active time per player.
- bool continuous                                                             : enables continuous force application upon player colliding with spring. 
- Vector3 continuousForce                                               : force applied over specified time.

There's also some test objects in the states.

2024-02-23 16:41 UTC, Odycious requested changes
Good! Just a few small changes :)

2024-02-23 16:41 UTC, Odycious commented on Client/States/GameplayState.cpp
> +    for (int i = 0; i < 4; i++) {
Refactor this into its own function

2024-02-23 16:41 UTC, Odycious commented on Server/CMakeLists.txt
> + "Components/Spring.h" "Components/Spring.cpp")
Follow style above.

2024-02-23 16:41 UTC, Odycious commented on Server/Components/Spring.cpp
> +		//std::cout << pushableObject[obj.first] << "\n";
Remove comment

2024-02-23 16:41 UTC, Odycious commented on Server/Components/Spring.cpp
> +	for (auto obj : pushableObject) {
This needs to be a reference you're making a copy of the object.

Go for auto& obj

2024-02-23 16:41 UTC, Odycious commented on Server/Components/Spring.cpp
> +	for (auto obj : tempList) {
Same again, see above, please make this into a reference.

2024-02-23 16:41 UTC, Odycious commented on Server/Components/Spring.h
> +    std::map<const GameObject*, float> pushableObject;
Please change this to an unordered_map instead of map. Map is Olog(n) worst case lookup, compared to O(1) unordered map.

2024-02-23 16:41 UTC, Odycious commented on Server/States/RunningState.cpp
> +    //* =================SPRING STUFF=================
Also move this into it's own function please.

2024-02-25 16:58 UTC, St4rman commented
Good job on the code! Very pleased with how fast you got this done and the jump pads have a few different angles they can shoot out at which is always appreciated. They're going to make the levels very dynamic and that's always good. 

Just a few style changes that need to be made but that's par for the course. 

Nicely done on figuring out the thigns in running state, game state, and replicated. The networking code is no joke. Once done, ill have you look at graphics as well since it's graphics sprint next. 

Excellent stuff :]

2024-02-27 14:29 UTC, Odycious approved these changes
Nice changes to the code, good work!

2024-02-27 14:33 UTC, merged