Marge Component system to main
The-Newcastle-Gang/SpeedFun pull request #8
Opened 2024-02-01 11:56 UTC by HeavyMetalGameDev

This involves:
-Component.h, component base class with Unity-like virtual methods for Start, Update, PhysicsUpdate and OnCollision methods.
-Added entt.hpp, external entity component system. We do not plan on using the ECS of this, but DO intend to use the signal functionality.
-Changes to GameObject.h to have methods which call all components at an appropriate time: when GameObject is Updated, calls Update() function on all components etc. Some of the new functionality uses shared pointers, some uses raw pointers purely because the codebase uses raw pointers and there is too much to change.

NOT IMPLEMENTED IN THIS BRANCH
- The methods of the GameObject are not called at any point, and need to be added in whichever class should call them. GameWorld must call the Update() function of GameObjects when looping though them, must also call Start() once all objects have been initialised.

2024-02-01 12:35 UTC, St4rman reviewed
lgtm !!!! :]

2024-02-01 13:08 UTC, St4rman approved these changes
lgtm part 2

2024-02-01 13:39 UTC, Joerseven requested changes
Still thinking about this, discussed as a group

2024-02-06 13:01 UTC, Joerseven requested changes, later dismissed
Suggestions put in!

2024-02-06 13:01 UTC, Joerseven commented on Replicated/Component.h
> +		virtual void PhysicsUpdate(float dt) {};
Rename fixed time over dt.

2024-02-06 13:01 UTC, Joerseven commented on CSC8503CoreClasses/GameObject.h
> +		void PhysicsUpdateAllComponents(float dt) { for (Component*& component : components)component->PhysicsUpdate(dt); }
Big memes

2024-02-06 13:01 UTC, Joerseven commented on CSC8503CoreClasses/GameObject.h
> +				T* typeCast = dynamic_cast<std::shared_ptr<T>>(component);
Normal pointer here.

2024-02-06 15:51 UTC, Odycious approved these changes

2024-02-06 15:53 UTC, merged